---
#Replaces Actor 513 EN_OBJ_HATENAB_BLOCK (Sprite 208)


source_files: [../src/environmentSFX.cpp]
hooks:
  - name: NewSoundSpawnerBuild
    type: add_func_pointer
    src_addr_pal: 0x80AFE754
    target_func: 'daMusicH::build()'